### ISSUE TITLE
webRTC推流部分

### ISSUE THREAD

**Issue by huiqiaoqiu** [metartc/yangwebrtc#1]
看了下项目大概结构，webRTC的推流实现部分是封在libYangAVLib2.a库里吗？

**Comment by yangrtc** [comment]
libYangAVLib2.a 这个代码刚上传了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangrtc/yangwebrtc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月13日(星期一) 下午4:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yangrtc/yangwebrtc] webRTC推流部分 (#1)





 
看了下项目大概结构，webRTC的推流实现部分是封在libYangAVLib2.a库里吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huiqiaoqiu** [comment]
看到提交记录了，学习学习
