### ISSUE TITLE
您好！可以提供一个demo项目吗

### ISSUE THREAD

**Issue by ThomasWind333** [metartc/yangwebrtc#2]
我这里配置这个项目有点问题
目前发现需要将.pro文件中的HOME_BASE设置为主目录的绝对路径才行
看readme中的说法，我先运行lib项目，再运行player项目，输入rtmp的链接，程序会crash掉。
之后我将预编译的dll库移入bin中程序表现正常了些。
另外需要将UI的大小拉大，才会有许多的运行代码提示，否则也是会crash掉。尽管有许多提示，但是最后也是crash，有点迷惑了。
环境搭建有些吃力，希望博主给个运行demo！

**Comment by yangrtc** [comment]
2.0.007版本yangplayer支持webrtc，rtmp支持还在开发中。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月16日(周四) 下午4:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yangrtc/yangwebrtc] 您好！可以提供一个demo项目吗 (#2)




 
我这里配置这个项目有点问题
 目前发现需要将.pro文件中的HOME_BASE设置为主目录的绝对路径才行
 看readme中的说法，我先运行lib项目，再运行player项目，输入rtmp的链接，程序会crash掉。
 之后我将预编译的dll库移入bin中程序表现正常了些。
 另外需要将UI的大小拉大，才会有许多的运行代码提示，否则也是会crash掉。尽管有许多提示，但是最后也是crash，有点迷惑了。
 环境搭建有些吃力，希望博主给个运行demo！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangrtc** [comment]
有问题也可以加入这个群里提问
### yangwebrtc服务群
![yangwebrtc1](https://user-images.githubusercontent.com/87118023/133870819-baac2335-3d81-4563-947b-9ca68d4ca6d8.jpg)

**Comment by zhuyanrobert** [comment]
加群的二维码过期了，麻烦作者更新一下，有问题想咨询
