### ISSUE TITLE
YangWebRTc有没有图片或者视频展示下呢？？？

### ISSUE THREAD

**Issue by excellentman2020** [metartc/yangwebrtc#3]
您好，请问YangWebRTc有没有图片或者视频展示下呢？？？

**Comment by yangrtc** [comment]
### yangwebrtc服务群
![yangwebrtc1](https://user-images.githubusercontent.com/87118023/133881762-a2453c7d-fa8b-4dec-8d1a-084384b23cdd.jpg)

**Comment by ludaojun** [comment]
二维码过起啦

**Comment by yangrtc** [comment]
readme.md 里的没有过期




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月30日(星期二) 下午3:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [metartc/yangwebrtc] YangWebRTc有没有图片或者视频展示下呢？？？ (#3)





 
二维码过起啦
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ludaojun** [comment]
ok
